// PROFILE
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const LIKE_USER = 'LIKE_USER';
// AUTH
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
// ERRORS
export const GET_ERRORS = 'GET_ERRORS';
// SOULMATCHER
export const GET_USERS = 'GET_USERS';
export const LOADING = 'LOADING';
// SEARCH
export const SEARCH_USERS = 'SEARCH_USERS';
// CHAT
export const GET_MATCHES = 'GET_MATCHES';
export const GET_MESSAGES = 'GET_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SET_CURRENT = 'SET_CURRENT';
// USER
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const CHANGE_INFOS = 'CHANGE_INFOS';
// NOTIFICATIONS
export const GET_NOTIFS = 'GET_NOTIFS';
export const NEW_NOTIF = 'NEW_NOTIF';
// SETTINGS
export const SET_RESPONSE = 'SET_RESPONSE';
//ADMIN
export const ADMIN_GET_STATS = 'ADMIN_GET_STATS';
export const ADMIN_GET_USERS = 'ADMIN_GET_USERS';
export const DELETE_USER = 'DELETE_USER';
export const BAN_USER = 'BAN_USER';
export const UNBAN_USER = 'UNBAN_USER';
export const GET_PRO_USERS = 'GET_PRO_USERS';
export const UPDATE_PRO_USER_STATUS = 'UPDATE_PRO_USER_STATUS';
export const UPDATE_PRO_USER_PAYMENT = 'UPDATE_PRO_USER_PAYMENT';
